const actionTypes = {
  SIGNUPFAIL: "SIGNUPFAIL",
  SIGNUPSUCCESS: "SIGNUPSUCCESS",
  SIGNINFAIL: "SIGNINFAIL",
  SIGNINSUCCESS: "SIGNINSUCCESS",
  CHANGE_LOGIN_STATE: "CHANGE_LOGIN_STATE"
};
export default actionTypes;
